[tool.poetry]
name = "eth-room-allocation"
version = "0.1.0"
description = ""
authors = [
  "Max Kieffer <maxkieffer@icloud.com>, Alex Thillen <alexthillen852@gmail.com>",
]
readme = "README.md"
packages = [{ include = "eth_room_allocation" }]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.3"
flask = "^2.3.2"
requests = "^2.31.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.1"
pylint = "^2.17.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins.pylint]
config_file = ".pylintrc"
